variables:
  MAVEN_OPTS: '-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true'
  MAVEN_CLI_OPTS: '--batch-mode --errors --fail-at-end --show-version'

cache:
  key: '$CI_JOB_NAME'
  paths:
    - '$CI_PROJECT_DIR/.m2/repository'

stages:
  - test

build:
  stage: test
  image: maven:3.6-jdk-11
  script:
    - 'mvn $MAVEN_CLI_OPTS verify'
