version: "3.1"

services:

  db:
    image: postgres:11.3
    container_name: prstatbucket-db
    restart: on-failure
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: prstatbucket
    volumes:
      - "./initdb:/docker-entrypoint-initdb.d:ro"
