logging:
  level:
    root: WARN

flyway:
  user: flyway
  password: flyway

db:
  server: localhost
  port: 5432
  database: prstatbucket
  user: prstatbucket
  password: prstatbucket

api:
  client-id: "${BITBUCKET_CLIENT_ID}"
  secret: "${BITBUCKET_CLIENT_SECRET}"

# Some sample public repositories to demo against; permissively licensed.
repositories:
  - atlassian/asap-java
  - atlassian/atlassian-annotations
  - chromiumembedded/cef
