logging:
  level:
    root: WARN

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  freemarker:
    cache: "true"
    expose-spring-macro-helpers: "true"
  resources:
    cache:
      cachecontrol:
        cache-public: "true"
        max-age: "365d"
    static-locations:
      - "classpath:/static/"
    chain:
      strategy:
        content:
          paths: "/js/**,/css/**"

flyway:
  user: flyway
  password: flyway

db:
  server: localhost
  port: 5432
  database: prstatbucket
  user: prstatbucket
  password: prstatbucket

api:
  client-id: "${BITBUCKET_CLIENT_ID}"
  secret: "${BITBUCKET_CLIENT_SECRET}"

# Some sample public repositories to demo against; permissively licensed.
repositories:
  - atlassian/asap-java
  - atlassian/atlassian-annotations
  - chromiumembedded/cef
